# Generated by Django 3.0 on 2021-09-01 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje total')),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=350, verbose_name='texto de la pregunta')),
                ('categoria', models.CharField(choices=[('A', 'Cultura y arte'), ('B', 'Historia'), ('C', 'Deporte'), ('D', 'Geografía'), ('E', 'Economía'), ('F', 'Ciencia y Educación'), ('G', 'Entretenimiento')], default=False, max_length=1, verbose_name='Elija la categoria de su pregunta elaborada')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='marque si es correcta')),
                ('descripcion', models.TextField(max_length=100, verbose_name='texto de la respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='quiz.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='Esta es la respuesta correcta?')),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje obtenido')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Participante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='quiz.Respuesta')),
            ],
        ),
    ]
