# Generated by Django 3.0 on 2021-08-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadísticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_Accesos', models.PositiveIntegerField(help_text='Hasta ahora se han logeado en Chaqueña Mente: f{PositiveIntegerField} personas')),
                ('Cantidad_Participantes', models.PositiveIntegerField(help_text='Hasta ahora han jugado Chaqueña Mente: f{PositiveIntegerField} personas')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correcta', models.BooleanField(verbose_name=True)),
                ('Descripcion', models.CharField(help_text='Inserte la pregunta', max_length=350)),
                ('Categoria', models.CharField(choices=[('A', 'Cultura y arte'), ('B', 'Historia'), ('C', 'Deporte'), ('D', 'Geografía'), ('E', 'Economía'), ('F', 'Ciencia y Educación'), ('G', 'Entretenimiento')], help_text='Elija la categoria de su pregunta elaborada', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje_General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(help_text='Escriba su Apellido', max_length=20)),
                ('Nombre', models.CharField(help_text='Escriba su Nombre', max_length=20)),
                ('Correo', models.EmailField(help_text='Escriba su correo eléctronico para registrarse y jugar!', max_length=254)),
                ('Contrasenia', models.CharField(help_text='Cree una contraseña para completar su registro', max_length=15)),
                ('Nombre_Usuario', models.CharField(help_text='Elija su nombre con el cual va a jugar!!!', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correcta', models.BooleanField(help_text='Indique cual es la respuesta correcta', verbose_name=True)),
                ('Descripción', models.CharField(help_text='Inserte las opciones de respuesta', max_length=100)),
                ('Id_Pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Id_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Usuario'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puntaje', models.PositiveIntegerField(help_text='Este es su puntaje hasta ahora:')),
                ('Tiempo', models.DurationField(help_text='¡Atención su tiempo va corriendo!')),
                ('Fecha', models.DateTimeField(default='America/Argentina/Buenos_Aires')),
                ('Compartir_TW_FB_IG', models.URLField(help_text='Hacé click para compartir tus exitos en tus redes', max_length=500)),
                ('Id_puntaje_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Puntaje_General')),
                ('Id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Usuario')),
                ('Ciudad', models.CharField(help_text='Escriba el nombre de su ciudad totalmente en MAYUSCULAS', max_length=25)),
                ('Id_puntaje_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Puntaje_General')),
            ],
            bases=('quiz.usuario',),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Usuario')),
                ('Id_Estadisticas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Estadísticas')),
            ],
            bases=('quiz.usuario',),
        ),
    ]
