# Generated by Django 3.0 on 2021-09-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='participante',
            new_name='quizParticipante',
        ),
    ]
