# Generated by Django 3.0 on 2021-09-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210903_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.TextField(max_length=350, verbose_name='texto de la respuesta'),
        ),
    ]
